### PR TITLE
fix broken Devanagari verses

### PR DESCRIPTION
**Pull request by vlastavesely**
The new versions taken from:
https://www.wisdomlib.org/hinduism/book/rig-veda-english-translation

### CODE REVIEW

**Comment by bkis** [comment]
Hi Vlasta,

thanks a lot for taking the time to contribute!  
The `.tei` files are generated from other sources curated by us. They are not meant to be edited manually, as any changes will be overwritten when the files are generated the next time. The Devanagari version used here is [this one](https://github.com/VedaWebProject/vedaweb-data/blob/main/rigveda/versions/eichler.csv) – also a file in this repository.

As this CSV contains the full content, I suspect there is an error in our transformation logic (the one generating the `.tei` files). Thank you for pointing this out to us! I will tag @an-fischer to raise awareness, as this is likely her move to make.

I am going to keep this PR open until we fixed the issue so you're informed whenever this happens. Again, thank you!

**Comment by an-fischer** [comment]
Thank you very much for pointing out this error! I identified the problem in our transformation logic, I will check whether it concerns other source data as well, and will let you know as soon as the problem is fixed.

**Comment by an-fischer** [comment]
Hallo Vlasta, we updated some of the data (mostly the morphological annotations) and also fixed the error in the transformation logic that made parts of Eichler's text (and also Aufrecht's by the way) disappear. So it should be fixed by now. Thanks again for pointing this out to us!

**Comment by vlastavesely** [comment]
Sehr gut, thanks for fixing this.

**Comment by bkis** [comment]
The update of the platform will go live ASAP – I think tomorrow might be realistic. Thanks again!

**Comment by vlastavesely** [comment]
Nicht zu danken. Have a nice day!

**Pull request closed without merging**
